<a href="https://colab.research.google.com/github/Aatmaj-Zephyr/Rank-of-a-matrix/blob/main/Rank_of_a_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Comparing the rank of a 3*3 matrix using the echolen form

In [ ]:
import torch

Let us make a matrix of a size, say 3*3

In [ ]:
a=torch.tensor([[2.,3,4],[5,4,3],[6,3,5]])
print(a)

tensor([[2., 3., 4.],
        [5., 4., 3.],
        [6., 3., 5.]])

Let's now reduce it to the echlon form by making the first element 1

In [ ]:
div=a[0][0]
a[0]=a[0]/div
print(a)

tensor([[1.0000, 1.5000, 2.0000],
        [5.0000, 4.0000, 3.0000],
        [6.0000, 3.0000, 5.0000]])


Let's now make the element below the first element equal to zero.

In [ ]:
a[1]=a[1]-a[1][0]*a[0]
print(a)

tensor([[ 1.0000,  1.5000,  2.0000],
        [ 0.0000, -3.5000, -7.0000],
        [ 6.0000,  3.0000,  5.0000]])


Similarly we continue for the next element

In [ ]:
a[2]=a[2]-a[2][0]*a[0]
print(a)

tensor([[ 1.0000,  1.5000,  2.0000],
        [ 0.0000, -3.5000, -7.0000],
        [ 0.0000, -6.0000, -7.0000]])


Now let's make the element at the last position equal to 0

In [ ]:
a[2]=a[2]-(a[1]*a[2][1]/a[1][1])
print(a)

tensor([[ 1.0000,  1.5000,  2.0000],
        [ 0.0000, -3.5000, -7.0000],
        [ 0.0000,  0.0000,  5.0000]])


Calculate the rank of the matrix

In [30]:
if(torch.equal(a[2],torch.zeros(3))):
 print("rank=",2)
else:
  print("rank=",3)

rank= 3
